{
 "title": "Crop Classification API Dashboard",
 "time": { "from": "2026-05-10T13:23:24.522Z", "to": "2026-05-10T16:27:46.707Z" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "errors" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{status_code=~\"5..\"}) or vector(0)\r\n\r\n",
     "legendFormat": "Total Errors"
    }
   ]
  },
  {
   "title": "App Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"fastapi_app\"}\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Predictions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{handler=\"/predict\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=~\"/predict|/health|/summary|/performance|/model-info|/\"}[1m])\r\n",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=~\"/predict|/summary|/performance|/model-info|/health|/\"}[5m]) / rate(http_request_duration_seconds_count{handler=~\"/predict|/summary|/performance|/model-info|/health|/\"}[5m])\r\n",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}