name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE: yourwhale/crops-classifications
  PYTHON_VERSION: "3.12"

jobs:
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Flake8
        run: |
          flake8 src/ --max-line-length=88 --ignore=E501,W503
      - name: Run Pylint
        run: |
          pylint src/**/*.py --fail-under=7.0 --disable=C0114,C0115,C0116
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Pull data from DVC
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: dvc pull

      - name: Created required directories
        run: |
          mkdir -p models reports

      - name: Run Pytest
        run: |
          pytest tests/ --cov=src/ --cov-report=xml

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: reports/
          retention-days: 7
